# Header
menu:
  Principal: /
  Arquivo: /archives
  "Perguntas Frequentes": /faq
rss: /atom.xml

# Content
excerpt_link: Ler Mais
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
